
import { drizzle } from "drizzle-orm/planetscale-serverless";
import { connect } from "@planetscale/database";
import { int, float, mysqlTable, varchar, date, boolean } from "drizzle-orm/mysql-core";


const env = {
  host: 'mysql://f2coocrsib7rlf7skslm:pscale_pw_fwTfCXcD3MdxM5X50d3mCuRW5ppUTrv6cBr21mNFZMO@aws.connect.psdb.cloud/dotstudio?ssl={"rejectUnauthorized":true}'
}


export const schools = mysqlTable("schools", {
  name: varchar("name", { length: 200 }),
  lat: float("lat"),
  long: float("long"),
  state: varchar("state", { length: 100 }),
  district: varchar("district", { length: 200 }),
  code: varchar("code", { length: 10 }),
  address: varchar("address", { length: 400 }),
  board: varchar("board", { length: 20 }),
  affiliationCode: int("affiliationCode").primaryKey(),
  principalName: varchar("principalName", { length: 120 }),
  principalContact: varchar("principalContact", { length: 20 }),
  principalEmail: varchar("principalEmail", { length: 50 }),
  principalRetirementDate: varchar("principalRetirementDate", { length: 100 }),
  contactNumber: varchar("contactNumber", { length: 20 }),
  email: varchar("email", { length: 50 }),
  website: varchar("website", { length: 200 }),
  faxNumber: varchar("faxNumber", { length: 20 }),
  landmark: varchar("landmark", { length: 200 }),
  establishmentYear: int("establishmentYear"),
  affiliationValidity: varchar("affiliationValidity", { length: 200 }),
  affiliationStatus: varchar("affiliationStatus", { length: 50 }),
  trustSocietyCompany: varchar("trustSocietyCompany", { length: 200 }),
  registrationDate: varchar("registrationDate", { length: 100 }),
  societyRegistrationNumber: varchar("societyRegistrationNumber", { length: 50 }),
  registrationValidity: varchar("registrationValidity", { length: 100 }),
  nocAuthority: varchar("nocAuthority", { length: 200 }),
  nocDate: varchar("nocDate", { length: 100 }),
  affiliationGrantYear: int("affiliationGrantYear"),
  basicDetailsLastUpdated: varchar("basicDetailsLastUpdated", { length: 100 }),

  totalTeachers: int("totalTeachers"),
  numberOfPGTs: int("numberOfPGTs"),
  numberOfTGTs: int("numberOfTGTs"),
  numberOfPRTs: int("numberOfPRTs"),
  numberOfPETs: int("numberOfPETs"),
  nonTeachingStaff: int("nonTeachingStaff"),
  trainedTeachers: int("trainedTeachers"),
  facultyTrainings: int("facultyTrainings"),
  facultDetailslastUpdated: varchar("facultDetailslastUpdated", { length: 100 }),

  
  grade1TotalSections: int("grade1TotalSections"),
  grade1TotalIntake: int("grade1TotalIntake"),
  grade1TotalStudents: int("grade1TotalStudents"),

  grade2TotalSections: int("grade2TotalSections"),
  grade2TotalIntake: int("grade2TotalIntake"),
  grade2TotalStudents: int("grade2TotalStudents"),

  grade3TotalSections: int("grade3TotalSections"),
  grade3TotalIntake: int("grade3TotalIntake"),
  grade3TotalStudents: int("grade3TotalStudents"),

  grade4TotalSections: int("grade4TotalSections"),
  grade4TotalIntake: int("grade4TotalIntake"),
  grade4TotalStudents: int("grade4TotalStudents"),

  grade5TotalSections: int("grade5TotalSections"),
  grade5TotalIntake: int("grade5TotalIntake"),
  grade5TotalStudents: int("grade5TotalStudents"),

  grade6TotalSections: int("grade6TotalSections"),
  grade6TotalIntake: int("grade6TotalIntake"),
  grade6TotalStudents: int("grade6TotalStudents"),

  grade7TotalSections: int("grade7TotalSections"),
  grade7TotalIntake: int("grade7TotalIntake"),
  grade7TotalStudents: int("grade7TotalStudents"),

  grade8TotalSections: int("grade8TotalSections"),
  grade8TotalIntake: int("grade8TotalIntake"),
  grade8TotalStudents: int("grade8TotalStudents"),

  grade9TotalSections: int("grade9TotalSections"),
  grade9TotalIntake: int("grade9TotalIntake"),
  grade9TotalStudents: int("grade9TotalStudents"),

  grade10TotalSections: int("grade10TotalSections"),
  grade10TotalIntake: int("grade10TotalIntake"),
  grade10TotalStudents: int("grade10TotalStudents"),

  grade11TotalSections: int("grade11TotalSections"),
  grade11TotalIntake: int("grade11TotalIntake"),
  grade11TotalStudents: int("grade11TotalStudents"),

  grade12TotalSections: int("grade12TotalSections"),
  grade12TotalIntake: int("grade12TotalIntake"),
  grade12TotalStudents: int("grade12TotalStudents"),

  gradeDetailsLastUpdated: varchar("gradeDetailsLastUpdated", { length: 100 }),

  subjectsOfferedForClass10: varchar("subjectsOfferedForClass10", { length: 1000 }),
  subjectsOfferedForClass12: varchar("subjectsOfferedForClass12", { length: 1000 }),
  subjectsOfferedlastUpdated: varchar("subjectsOfferedlastUpdated", { length: 100 }),

  totalSites: int("totalSites"),
  guardsEmployed: boolean("guardsEmployed"),
  schoolArea: float("schoolArea"),
  totalPlaygrounds: int("totalPlaygrounds"),
  playgroundArea: float("playgroundArea"),
  totalRooms: int("totalRooms"),
  smallRooms: int("smallRooms"),
  mediumRooms: int("mediumRooms"),
  largeRooms: int("largeRooms"),
  maleRestRooms: int("maleRestRooms"),
  totalToilets: int("totalToilets"),
  femaleRestRooms: int("femaleRestRooms"),
  boysToilets: int("boysToilets"),
  differentlyAbledToilets: int("differentlyAbledToilets"),
  femaleStaffWashrooms: int("femaleStaffWashrooms"),
  maleStaffWashrooms: int("maleStaffWashrooms"),
  totalLibraries: int("totalLibraries"),
  totalLaboratories: int("totalLaboratories"),
  studentCanteens: int("studentCanteens"),
  waterPurifiers: int("waterPurifiers"),
  staffCanteens: int("staffCanteens"),
  auditoriums: int("auditoriums"),
  liftsElevators: int("liftsElevators"),
  digitalClassrooms: int("digitalClassrooms"),
  hostelFacility: boolean("hostelFacility"),
  buildingBlocks: int("buildingBlocks"),
  fireExtinguishers: boolean("fireExtinguishers"),
  sprinklers: boolean("sprinklers"),
  cctvCameras: boolean("cctvCameras"),
  computersInLab: int("computersInLab"),
  examinationCenter: boolean("examinationCenter"),
  webServers: boolean("webServers"),
  boundaryWall: boolean("boundaryWall"),
  clinicFacility: boolean("clinicFacility"),
  barrierFreeRamps: boolean("barrierFreeRamps"),
  strongRoom: boolean("strongRoom"),
  gymnasium: boolean("gymnasium"),
  wifiEnabled: boolean("wifiEnabled"),
  indoorGames: boolean("indoorGames"),
  fireAlarms: boolean("fireAlarms"),
  sportsFacility: boolean("sportsFacility"),
  webBasedLearning: boolean("webBasedLearning"),
  swimmingPool: boolean("swimmingPool"),
  danceMusicFacility: boolean("danceMusicFacility"),
  busesOwned: int("busesOwned"),
  busesHired: int("busesHired"),
  vansMatadors: int("vansMatadors"),
  femaleBusAttendants: int("femaleBusAttendants"),
  totalDrivers: int("totalDrivers"),
  activityRooms: int("activityRooms"),
  transportCoordinator: varchar("transportCoordinator", { length: 200 }),
  transportCoordinatorContact: varchar("transportCoordinatorContact", { length: 20 }),
  rampsForDifferentlyAbled: boolean("rampsForDifferentlyAbled"),
  outdoorSportsFacility: boolean("outdoorSportsFacility"),
  infraLastUpdated: varchar("infraLastUpdated", { length: 100 }),

  nearestBank: varchar("nearestBank", { length: 200 }),
  distanceToBank: float("distanceToBank"),
  nearestBusStation: varchar("nearestBusStation", { length: 200 }),
  distanceToBusStation: float("distanceToBusStation"),
  nearestRailwayStation: varchar("nearestRailwayStation", { length: 200 }),
  distanceToRailwayStation: float("distanceToRailwayStation"),
  nearestAirport: varchar("nearestAirport", { length: 200 }),
  distanceToAirport: float("distanceToAirport"),
  nearestHospital: varchar("nearestHospital", { length: 200 }),
  distanceToHospital: float("distanceToHospital"),
  nearestPoliceStation: varchar("nearestPoliceStation", { length: 200 }),
  distanceToPoliceStation: float("distanceToPoliceStation"),
  nearestMetroStation: varchar("nearestMetroStation", { length: 200 }),
  distanceToMetroStation: float("distanceToMetroStation"),
  locationDetailsLastUpdated: varchar("locationDetailsLastUpdated", { length: 100 }),

  rainWaterHarvesting: boolean("rainWaterHarvesting"),
  roofWaterHarvesting: boolean("roofWaterHarvesting"),
  waterRecycling: boolean("waterRecycling"),
  waterFacilitiesMaintenance: boolean("waterFacilitiesMaintenance"),
  wasteSegregation: boolean("wasteSegregation"),
  organicWasteRecycling: boolean("organicWasteRecycling"),
  paperWasteRecycling: boolean("paperWasteRecycling"),
  paperReductionEfforts: boolean("paperReductionEfforts"),
  solidWasteDisposal: boolean("solidWasteDisposal"),
  electronicWasteDisposal: boolean("electronicWasteDisposal"),
  energyEfficientEquipment: boolean("energyEfficientEquipment"),
  plantation: boolean("plantation"),
  dripIrrigation: boolean("dripIrrigation"),
  solarEnergyUse: boolean("solarEnergyUse"),
  roPlantWaterRecycling: boolean("roPlantWaterRecycling"),
  environmentalAwarenessPromotion: boolean("environmentalAwarenessPromotion"),
  waterAuditEducation: boolean("waterAuditEducation"),
  studentWaterAuditing: boolean("studentWaterAuditing"),
  environmentalLiteracy: boolean("environmentalLiteracy"),
  treesPlanted: int("treesPlanted"),
  environmentProtectionLastUpdated: varchar("environmentProtectionLastUpdated", { length: 100 }),

  tenthPassPercentage: varchar("10thPassPercentage", {length: 50 }),
  twelfthPassPercentage: varchar("12thPassPercentage", {length: 50 }),
  wellnessTeacher: varchar("wellnessTeacher", { length: 120 }),
  grievanceOfficer: varchar("grievanceOfficer", { length: 120 }),
  grievanceOfficerContact: varchar("grievanceOfficerContact", { length: 20 }),
  grievanceOfficerEmail: varchar("grievanceOfficerEmail", { length: 50 }),
  harassmentCommitteeHead: varchar("harassmentCommitteeHead", { length: 120 }),
  harassmentCommitteeContact: varchar("harassmentCommitteeContact", { length: 20 }),
  harassmentCommitteeEmail: varchar("harassmentCommitteeEmail", { length: 50 }),
  emergencyContactPerson: varchar("emergencyContactPerson", { length: 120 }),
  emergencyContactNumber: varchar("emergencyContactNumber", { length: 20 }),
  emergencyContactEmail: varchar("emergencyContactEmail", { length: 50 }),
  numberOfDoctors: int("numberOfDoctors"),
  numberOfNurses: int("numberOfNurses"),
  numberOfBeds: int("numberOfBeds"),
  parentTeacherAssociation: varchar("parentTeacherAssociation", { length: 10 }),
  teachersGrade: varchar("teachersGrade", { length: 50 }),
  staffSalaryTiming: varchar("staffSalaryTiming", { length: 50 }),
  epfFacility: varchar("epfFacility", { length: 10 }),
  epfRegistrationNumber: varchar("epfRegistrationNumber", { length: 50 }),
  salaryPaymentMode: varchar("salaryPaymentMode", { length: 50 }),
  bankWithSalaryAccount: varchar("bankWithSalaryAccount", { length: 120 }),
  accountsAudit: varchar("accountsAudit", { length: 10 }),
  cbseInvolvementLevel: varchar("cbseInvolvementLevel", { length: 50 }),
  academicSession: varchar("academicSession", { length: 50 }),
  vacationPeriod: varchar("vacationPeriod", { length: 50 }),
  bestPractices: varchar("bestPractices", { length: 500 }),
  eLearningDevelopment: varchar("eLearningDevelopment", { length: 500 }),
  vitalInformationLastUpdated: varchar("vitalInformationLastUpdated", { length: 100 }),

  admissionFeeSeniorSecondary: int("admissionFeeSeniorSecondary"),
  admissionFeeSecondary: int("admissionFeeSecondary"),
  admissionFeeMiddle: int("admissionFeeMiddle"),
  admissionFeePrimary: int("admissionFeePrimary"),
  tuitionFeeSeniorSecondary: int("tuitionFeeSeniorSecondary"),
  feesCalculated: int("feesCalculated"),
  category: varchar("category", { length: 50 }),
  tuitionFeeSecondary: int("tuitionFeeSecondary"),
  tuitionFeeMiddle: int("tuitionFeeMiddle"),
  tuitionFeePrimary: int("tuitionFeePrimary"),
  yearlyDevChargesSeniorSecondary: int("yearlyDevChargesSeniorSecondary"),
  yearlyDevChargesSecondary: int("yearlyDevChargesSecondary"),
  yearlyDevChargesMiddle: int("yearlyDevChargesMiddle"),
  yearlyDevChargesPrimary: int("yearlyDevChargesPrimary"),
  otherChargesSeniorSecondary: int("otherChargesSeniorSecondary"),
  otherChargesSecondary: int("otherChargesSecondary"),
  otherChargesMiddle: int("otherChargesMiddle"),
  otherChargesPrimary: int("otherChargesPrimary"),
  feeStructureLastUpdated: varchar("feeStructureLastUpdated", { length: 100 }),

  udiseCode: varchar("udiseCode", { length: 20 }),
  location: varchar("location", { length: 20 }),  // Assuming this is either "rural" or "urban"
  habitationName: varchar("habitationName", { length: 200 }),
  villageWardName: varchar("villageWardName", { length: 200 }), 
  villagePanchayatName: varchar("villagePanchayatName", { length: 200 }), 
  pinCode: varchar("pinCode", { length: 6 }),  
  clusterResourceCenterName: varchar("clusterResourceCenterName", { length: 200 }), 
  cdBlockName: varchar("cdBlockName", { length: 200 }), 
  educationZoneName: varchar("educationZoneName", { length: 200 }),
  assemblyConstituency: varchar("assemblyConstituency", { length: 200 }), 
  municipality: varchar("municipality", { length: 200 }), 
  allWeatherRoadAccess: boolean("allWeatherRoadAccess"),  
  isSpecialSchool: boolean("isSpecialSchool"),  
  isShiftSchool: boolean("isShiftSchool"), 
  isResidentialSchool: boolean("isResidentialSchool"),
  residentialSchoolType: varchar("residentialSchoolType", { length: 100 }), 
  isReligiousMinoritySchool: boolean("isReligiousMinoritySchool"),  
  religiousMinoritySchoolType: varchar("religiousMinoritySchoolType", { length: 100 }),
  academicInspections: int("academicInspections"),  
  crcCoordinatorVisits: int("crcCoordinatorVisits"),
  blockOfficerVisits: int("blockOfficerVisits"),
  additionalInformationlastUpdated: varchar("additionalInformationlastUpdated", { length: 100 }),

  instructionalDaysLastYear: int("instructionalDaysLastYear"),
  schoolHoursChildren: float("schoolHoursChildren"),
  schoolHoursTeachers: float("schoolHoursTeachers"),
  isCCEImplemented: boolean("isCCEImplemented"),
  areRecordsMaintained: boolean("areRecordsMaintained"),
  areRecordsShared: boolean("areRecordsShared"),
  studentsSpecialTrainingCurrent: int("studentsSpecialTrainingCurrent"),
  studentsEnrolledSpecialTrainingLast: int("studentsEnrolledSpecialTrainingLast"),
  studentsCompletedSpecialTrainingLast: int("studentsCompletedSpecialTrainingLast"),
  hasSMC: boolean("hasSMC"),
  languagesTaught: varchar("languagesTaught", { length: 100 }),
  isAnganwadiNear: boolean("isAnganwadiNear"),
  SMCMeetingsLastYear: int("SMCMeetingsLastYear"),
  doesSMCPreparePlan: boolean("doesSMCPreparePlan"),
  hasSeparateSMCAccount: boolean("hasSeparateSMCAccount"),
  bankName: varchar("bankName", { length: 100 }),
  accountHolderName: varchar("accountHolderName", { length: 100 }),
  accountNumber: varchar("accountNumber", { length: 50 }),
  IFSCCode: varchar("IFSCCode", { length: 20 }),
  textbookReceivedDate: varchar("textbookReceivedDate", { length: 100 }),
  hasCompleteSetTLE: boolean("hasCompleteSetTLE"),
  hasTLEReceivedEachGrade: boolean("hasTLEReceivedEachGrade"),
  hasPlayMaterialEachGrade: boolean("hasPlayMaterialEachGrade"),
  isMotherTongueUsed: boolean("isMotherTongueUsed"),
  lastUpdatedSchoolParticularsElementary: varchar("lastUpdatedSchoolParticularsElementary", { length: 100 }),
  instructionalDaysLastYearSecondary: int("instructionalDaysLastYearSecondary"),
  schoolHoursChildrenSecondary: float("schoolHoursChildrenSecondary"),
  schoolHoursTeachersSecondary: float("schoolHoursTeachersSecondary"),
  isCCEImplementedSecondary: boolean("isCCEImplementedSecondary"),
  areSMCAndSMDCSame: boolean("areSMCAndSMDCSame"),
  lastUpdatedSchoolParticularsSecondary: varchar("lastUpdatedSchoolParticularsSecondary", { length: 100 }),

  puccaClassrooms: int("puccaClassrooms"),
  partiallyPuccaClassrooms: int("partiallyPuccaClassrooms"),
  kuchchaClassrooms: int("kuchchaClassrooms"),
  tentClassrooms: int("tentClassrooms"),
  landForExpansion: boolean("landForExpansion"),
  roomForPrincipal: boolean("roomForPrincipal"),
  roomForVicePrincipal: boolean("roomForVicePrincipal"),
  roomForCoCurricular: boolean("roomForCoCurricular"),
  staffQuarters: boolean("staffQuarters"),
  handWashingFacility: boolean("handWashingFacility"),
  electricity: boolean("electricity"),
  publicAddressSystem: boolean("publicAddressSystem"),
  projector: boolean("projector"),
  printerCount: int("printerCount"),
  printerSpeed: varchar("printerSpeed", { length: 30 }),
  photocopierCount: int("photocopierCount"),
  leaseLine: boolean("leaseLine"),
  leaseLineSpeed: int("leaseLineSpeed"),
  scanner: boolean("scanner"),
  physicalFacilitiesLastUpdated: varchar("physicalFacilitiesLastUpdated", { length: 100 }),

  primaryGeneral: int("primaryGeneral"),
  primarySC: int("primarySC"),
  primaryST: int("primaryST"),
  primaryOBC: int("primaryOBC"),
  middleGeneral: int("middleGeneral"),
  middleSC: int("middleSC"),
  middleST: int("middleST"),
  middleOBC: int("middleOBC"),
  secondaryGeneral: int("secondaryGeneral"),
  secondarySC: int("secondarySC"),
  secondaryST: int("secondaryST"),
  secondaryOBC: int("secondaryOBC"),
  seniorSecondaryGeneral: int("seniorSecondaryGeneral"),
  seniorSecondarySC: int("seniorSecondarySC"),
  seniorSecondaryST: int("seniorSecondaryST"),
  seniorSecondaryOBC: int("seniorSecondaryOBC"),
  primaryMuslim: int("primaryMuslim"),
  primaryChristian: int("primaryChristian"),
  primarySikh: int("primarySikh"),
  primaryJain: int("primaryJain"),
  primaryOther: int("primaryOther"),
  middleMuslim: int("middleMuslim"),
  middleChristian: int("middleChristian"),
  middleSikh: int("middleSikh"),
  middleJain: int("middleJain"),
  middleOther: int("middleOther"),
  secondaryMuslim: int("secondaryMuslim"),
  secondaryChristian: int("secondaryChristian"),
  secondarySikh: int("secondarySikh"),
  secondaryJain: int("secondaryJain"),
  secondaryOther: int("secondaryOther"),
  seniorSecondaryMuslim: int("seniorSecondaryMuslim"),
  seniorSecondaryChristian: int("seniorSecondaryChristian"),
  seniorSecondarySikh: int("seniorSecondarySikh"),
  seniorSecondaryJain: int("seniorSecondaryJain"),
  seniorSecondaryOther: int("seniorSecondaryOther"),
  
  grade1VisualImpairment: int("grade1VisualImpairment"),
  grade1SpeechImpairment: int("grade1SpeechImpairment"),
  grade1LocomotiveDisability: int("grade1LocomotiveDisability"),
  grade1HearingImpairment: int("grade1HearingImpairment"),
  grade1CerebralPalsy: int("grade1CerebralPalsy"),
  grade1LearningDisability: int("grade1LearningDisability"),
  grade1Autism: int("grade1Autism"),
  grade1MultipleDisabilities: int("grade1MultipleDisabilities"),

  grade2VisualImpairment: int("grade2VisualImpairment"),
  grade2SpeechImpairment: int("grade2SpeechImpairment"),
  grade2LocomotiveDisability: int("grade2LocomotiveDisability"),
  grade2HearingImpairment: int("grade2HearingImpairment"),
  grade2CerebralPalsy: int("grade2CerebralPalsy"),
  grade2LearningDisability: int("grade2LearningDisability"),
  grade2Autism: int("grade2Autism"),
  grade2MultipleDisabilities: int("grade2MultipleDisabilities"),

  grade3VisualImpairment: int("grade3VisualImpairment"),
  grade3SpeechImpairment: int("grade3SpeechImpairment"),
  grade3LocomotiveDisability: int("grade3LocomotiveDisability"),
  grade3HearingImpairment: int("grade3HearingImpairment"),
  grade3CerebralPalsy: int("grade3CerebralPalsy"),
  grade3LearningDisability: int("grade3LearningDisability"),
  grade3Autism: int("grade3Autism"),
  grade3MultipleDisabilities: int("grade3MultipleDisabilities"),

  grade4VisualImpairment: int("grade4VisualImpairment"),
  grade4SpeechImpairment: int("grade4SpeechImpairment"),
  grade4LocomotiveDisability: int("grade4LocomotiveDisability"),
  grade4HearingImpairment: int("grade4HearingImpairment"),
  grade4CerebralPalsy: int("grade4CerebralPalsy"),
  grade4LearningDisability: int("grade4LearningDisability"),
  grade4Autism: int("grade4Autism"),
  grade4MultipleDisabilities: int("grade4MultipleDisabilities"),

  grade5VisualImpairment: int("grade5VisualImpairment"),
  grade5SpeechImpairment: int("grade5SpeechImpairment"),
  grade5LocomotiveDisability: int("grade5LocomotiveDisability"),
  grade5HearingImpairment: int("grade5HearingImpairment"),
  grade5CerebralPalsy: int("grade5CerebralPalsy"),
  grade5LearningDisability: int("grade5LearningDisability"),
  grade5Autism: int("grade5Autism"),
  grade5MultipleDisabilities: int("grade5MultipleDisabilities"),

  grade6VisualImpairment: int("grade6VisualImpairment"),
  grade6SpeechImpairment: int("grade6SpeechImpairment"),
  grade6LocomotiveDisability: int("grade6LocomotiveDisability"),
  grade6HearingImpairment: int("grade6HearingImpairment"),
  grade6CerebralPalsy: int("grade6CerebralPalsy"),
  grade6LearningDisability: int("grade6LearningDisability"),
  grade6Autism: int("grade6Autism"),
  grade6MultipleDisabilities: int("grade6MultipleDisabilities"),

  grade7VisualImpairment: int("grade7VisualImpairment"),
  grade7SpeechImpairment: int("grade7SpeechImpairment"),
  grade7LocomotiveDisability: int("grade7LocomotiveDisability"),
  grade7HearingImpairment: int("grade7HearingImpairment"),
  grade7CerebralPalsy: int("grade7CerebralPalsy"),
  grade7LearningDisability: int("grade7LearningDisability"),
  grade7Autism: int("grade7Autism"),
  grade7MultipleDisabilities: int("grade7MultipleDisabilities"),

  grade8VisualImpairment: int("grade8VisualImpairment"),
  grade8SpeechImpairment: int("grade8SpeechImpairment"),
  grade8LocomotiveDisability: int("grade8LocomotiveDisability"),
  grade8HearingImpairment: int("grade8HearingImpairment"),
  grade8CerebralPalsy: int("grade8CerebralPalsy"),
  grade8LearningDisability: int("grade8LearningDisability"),
  grade8Autism: int("grade8Autism"),
  grade8MultipleDisabilities: int("grade8MultipleDisabilities"),

  grade9VisualImpairment: int("grade9VisualImpairment"),
  grade9SpeechImpairment: int("grade9SpeechImpairment"),
  grade9LocomotiveDisability: int("grade9LocomotiveDisability"),
  grade9HearingImpairment: int("grade9HearingImpairment"),
  grade9CerebralPalsy: int("grade9CerebralPalsy"),
  grade9LearningDisability: int("grade9LearningDisability"),
  grade9Autism: int("grade9Autism"),
  grade9MultipleDisabilities: int("grade9MultipleDisabilities"),

  grade11VisualImpairment: int("grade11VisualImpairment"),
  grade11SpeechImpairment: int("grade11SpeechImpairment"),
  grade11LocomotiveDisability: int("grade11LocomotiveDisability"),
  grade11HearingImpairment: int("grade11HearingImpairment"),
  grade11CerebralPalsy: int("grade11CerebralPalsy"),
  grade11LearningDisability: int("grade11LearningDisability"),
  grade11Autism: int("grade11Autism"),
  grade11MultipleDisabilities: int("grade11MultipleDisabilities"),

  grade12VisualImpairment: int("grade12VisualImpairment"),
  grade12SpeechImpairment: int("grade12SpeechImpairment"),
  grade12LocomotiveDisability: int("grade12LocomotiveDisability"),
  grade12HearingImpairment: int("grade12HearingImpairment"),
  grade12CerebralPalsy: int("grade12CerebralPalsy"),
  grade12LearningDisability: int("grade12LearningDisability"),
  grade12Autism: int("grade12Autism"),
  grade12MultipleDisabilities: int("grade12MultipleDisabilities"),


  enrollmentLastUpdated: varchar("enrollmentLastUpdated", { length: 100 }),

  kitchenShedStatus: varchar("kitchenShedStatus", { length: 20 }),
  mealSource: varchar("mealSource", { length: 50 }),
  mealLastUpdated: varchar("mealLastUpdated", { length: 100 }),
  
  aerobics: boolean("aerobics"),
  archery: boolean("archery"),
  athletics: boolean("athletics"),
  badminton: boolean("badminton"),
  basketball: boolean("basketball"),
  boxing: boolean("boxing"),
  chess: boolean("chess"),
  cricket: boolean("cricket"),
  football: boolean("football"),
  gymnastics: boolean("gymnastics"),
  handball: boolean("handball"),
  hockey: boolean("hockey"),
  judo: boolean("judo"),
  kabaddi: boolean("kabaddi"),
  khoKho: boolean("khoKho"),
  shooting: boolean("shooting"),
  swimming: boolean("swimming"),
  taekwondo: boolean("taekwondo"),
  tableTennis: boolean("tableTennis"),
  tennis: boolean("tennis"),
  volleyball: boolean("volleyball"),
  yoga: boolean("yoga"),
  sportsLastUpdated: varchar("sportsLastUpdated", { length: 100 }),
});

// create the connection
const connection = connect({
  url: env.host,
});

export const db = drizzle(connection);

// export const migrateToLatest = async () => {
//   await migrate(DB, { migrationsFolder: "services/core/db/migrations" });
// };
