import './globals.css'
import React from 'react'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

// import main from '../api/schema'
// import main, { headerMap } from '../api/main'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  // await main()
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
